"""add verify_password and @property

Revision ID: 28de81bc4c7c
Revises: f34b9418bf31
Create Date: 2022-02-05 11:22:14.785744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28de81bc4c7c'
down_revision = 'f34b9418bf31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
