"""added pitch column

Revision ID: 53500051f076
Revises: f4d26945132d
Create Date: 2022-02-06 12:39:11.456577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53500051f076'
down_revision = 'f4d26945132d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitch', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'pitch')
    # ### end Alembic commands ###
