"""added biography and profile_pic

Revision ID: 6b08b6c0e28d
Revises: 33bc27316fdd
Create Date: 2022-02-04 21:44:58.538053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b08b6c0e28d'
down_revision = '33bc27316fdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('biography', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('profile_pic', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_pic')
    op.drop_column('user', 'biography')
    # ### end Alembic commands ###
