"""removed pitch column

Revision ID: f4d26945132d
Revises: 8fb0c0ba2a5b
Create Date: 2022-02-06 12:38:52.741242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4d26945132d'
down_revision = '8fb0c0ba2a5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'pitch')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitch', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
